///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ImgurResponse {
/*
{
  "status": "success",
  "statusCode": 200,
  "data": [
    "https://giuki.online/uploads/66a0b7c477a2517218088360.png"
  ]
} 
*/

  String? status;
  int? statusCode;
  List<String?>? data;

  ImgurResponse({
    this.status,
    this.statusCode,
    this.data,
  });
  ImgurResponse.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    statusCode = int.tryParse(json['statusCode']?.toString() ?? '');
    if (json['data'] != null && (json['data'] is List)) {
      final v = json['data'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['statusCode'] = statusCode;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['data'] = arr0;
    }
    return data;
  }
}
